[package]
name = "{{crate_name}}"
version = "0.0.0"
edition = "2021"
license = "BSD-2-Clause"
description = "{{description}}"
authors = ["{{author}}"]
readme = "README.md"

[dependencies]

[dev-dependencies]