[package]
name = "{{crate_name}}"
version = "0.0.0"
edition = "2018"
license = "BSD-2-Clause"
description = "{{description}}"
authors = ["{{authors}}"]
readme = "README.md"

[dependencies]

[dev-dependencies]